apiVersion: v1
kind: Pod
metadata:
  name: node-bad-selector
  namespace: three-tier-app
spec:
  nodeSelector:
    kubernetes.io/hostname: no-such-node-hostname
  containers:
    - name: app
      image: nginx:alpine
