apiVersion: v1
kind: Pod
metadata:
  name: pod-bad-probefail
  namespace: three-tier-app
spec:
  containers:
    - name: app
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /this-path-does-not-exist
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 2
