apiVersion: v1
kind: Pod
metadata:
  name: pod-bad-imagepull
  namespace: three-tier-app
spec:
  containers:
    - name: app
      image: nginx:this-tag-does-not-exist
      imagePullPolicy: IfNotPresent
